package com.choruskube.core.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.util.Map;
import java.util.UUID;

/**
 * @param hostname identifies the Worker process for operator display and revocation
 * @param instanceId generated by the Worker process at startup and re-sent on every
 *     registration, so repeated registrations from the same still-running process update one
 *     Worker record instead of accumulating one per token renewal
 * @param capabilities probed facts about the Worker's own infrastructure — e.g. sysbox presence,
 *     Pod Security Admission level, available RuntimeClasses, Kubernetes version. A registrar that
 *     records required capabilities can reject a Worker that cannot provide them before a run
 *     starts, rather than failing later as a Pending pod with an opaque scheduling error.
 */
public record WorkerRegisterRequest(
        @NotBlank String hostname, @NotNull UUID instanceId, Map<String, String> capabilities) {}
