#!/usr/bin/env bash
# Applies the dependency-proxy cache contract. When DEP_PROXY_BASE is set, routes
# Go/npm/Gradle dependency fetches through an in-cluster proxy; when unset, no-op
# (tools hit their public defaults). Safe to source in CI and in the agent pod.
apply_dep_proxy() {
  local gradle_home="${1:?usage: apply_dep_proxy <gradle_user_home>}"
  local base="${DEP_PROXY_BASE:-}"
  [ -z "$base" ] && return 0

  export GOPROXY="${base}/repository/go-proxy/,direct"
  export GOSUMDB="off"
  export npm_config_registry="${base}/repository/npm-proxy/"

  mkdir -p "${gradle_home}/init.d"
  cat > "${gradle_home}/init.d/dep-proxy.init.gradle" <<EOF
// Auto-generated by scripts/lib/dep-proxy.sh — routes Maven resolution through the
// in-cluster dependency proxy. Absent unless DEP_PROXY_BASE was set at apply time.
def mirror = "${base}/repository/maven-central/"
settingsEvaluated { settings ->
    settings.pluginManagement.repositories {
        maven { url mirror }
        gradlePluginPortal()
    }
    settings.dependencyResolutionManagement.repositories {
        maven { url mirror }
    }
}
allprojects {
    buildscript.repositories { maven { url mirror } }
    repositories { maven { url mirror } }
}
EOF
}
