#!/usr/bin/env bash
# scripts/setup.sh — Interactively configure secrets for a real ChorusKube run.
#
# Prompts one input at a time and writes a gitignored .env at the repo root that
# docker compose auto-loads. All credentials are OPTIONAL: the stack boots and
# serves the full API with none of them. The Claude token is needed to run AI
# agent nodes; a GitHub credential (PAT or App) is needed only to push / open PRs
# against a target repo.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
SECRETS_DIR="$REPO_ROOT/.secrets"

if [[ -f "$ENV_FILE" ]]; then
  read -r -p ".env already exists. Overwrite it? [y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]] || { echo "Keeping existing .env. Nothing changed."; exit 0; }
fi

CLAUDE_TOKEN="" ; PAT="" ; APP_ID="" ; APP_INSTALL="" ; APP_KEY_PATH=""

# 1) Claude token
echo
echo "1) Claude Code OAuth token — required to run AI agent nodes."
if command -v claude >/dev/null 2>&1; then
  read -r -p "   Run 'claude setup-token' now to generate one? [y/N] " ans
  # '|| true' so a failed/cancelled setup-token falls through to the paste prompt
  # below instead of aborting the whole script under 'set -e'.
  if [[ "$ans" =~ ^[Yy]$ ]]; then
    CLAUDE_TOKEN="$(claude setup-token)" || true
  fi
fi
if [[ -z "$CLAUDE_TOKEN" ]]; then
  read -r -s -p "   Paste a Claude token (or leave blank to skip): " CLAUDE_TOKEN ; echo
fi

# 2) GitHub credential
echo
echo "2) GitHub credential — needed only to push / open PRs against a target repo."
echo "   [1] None   [2] Personal Access Token (PAT)   [3] GitHub App"
read -r -p "   Choose [1/2/3] (default 1): " choice
case "${choice:-1}" in
  2)
    read -r -s -p "   Paste GitHub PAT: " PAT ; echo
    ;;
  3)
    read -r -p "   GitHub App ID: " APP_ID
    read -r -p "   Installation ID: " APP_INSTALL
    read -r -p "   Path to App private-key .pem on this host: " pem_src
    [[ -f "$pem_src" ]] || { echo "   ERROR: no file at '$pem_src'" >&2; exit 1; }
    mkdir -p "$SECRETS_DIR" ; chmod 700 "$SECRETS_DIR"
    cp "$pem_src" "$SECRETS_DIR/github-app.pem" ; chmod 600 "$SECRETS_DIR/github-app.pem"
    APP_KEY_PATH="/run/secrets/github-app.pem"
    ;;
  *) ;;
esac

# Write .env (only the values that were set)
{
  echo "# Generated by scripts/setup.sh — gitignored, never commit."
  [[ -n "$CLAUDE_TOKEN" ]] && echo "CLAUDE_CODE_OAUTH_TOKEN=$CLAUDE_TOKEN"
  [[ -n "$PAT" ]]          && echo "GITHUB_PAT=$PAT"
  [[ -n "$APP_ID" ]]       && echo "GITHUB_APP_ID=$APP_ID"
  [[ -n "$APP_INSTALL" ]]  && echo "GITHUB_APP_INSTALLATION_ID=$APP_INSTALL"
  [[ -n "$APP_KEY_PATH" ]] && echo "GITHUB_APP_PRIVATE_KEY_PATH=$APP_KEY_PATH"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

hint() { local s="$1"; [[ ${#s} -ge 4 ]] && printf '…%s' "${s: -4}" || printf '(set)'; }
echo
echo "Wrote $ENV_FILE:"
[[ -n "$CLAUDE_TOKEN" ]] && echo "  CLAUDE_CODE_OAUTH_TOKEN     $(hint "$CLAUDE_TOKEN")"
[[ -n "$PAT" ]]          && echo "  GITHUB_PAT                  $(hint "$PAT")"
[[ -n "$APP_ID" ]]       && echo "  GITHUB_APP_ID               $APP_ID"
[[ -n "$APP_INSTALL" ]]  && echo "  GITHUB_APP_INSTALLATION_ID  $APP_INSTALL"
[[ -n "$APP_KEY_PATH" ]] && echo "  GITHUB_APP_PRIVATE_KEY_PATH $APP_KEY_PATH (.secrets/github-app.pem)"

echo
read -r -p "Start the stack now with ./scripts/up.sh? [Y/n] " ans
[[ "$ans" =~ ^[Nn]$ ]] || exec "$SCRIPT_DIR/up.sh"
